### PR TITLE
Add Snap and Flatpak update for func_m and func_u

### PR DESCRIPTION
**Pull request by puxplaying**
Hi what do you think about to add Flatpak and Snap support to PacUI?
Here is my first try to add support to func_m and func_u 

Ps: The list functions of both Flatpak and Snap are currently not used but i thought it could may be added as a extra option in the TUI to list those installed packages. 

Please let me know what you think about.
Best Regards

### CODE REVIEW

**Comment by excalibur1234** [comment]
sorry for the delay, but i had problems with my github account.

i take a look at this PR soon - i hope before the weekend. please have a little more patience.

**Comment by excalibur1234** [comment]
i am unsure how to integrate snap and flatpak support in pacui.

i just installed snapd and flatpak:
 - snap search <Package Name> does not return anything, but complains about the server not reachable.
 - when i tested snap last, i noticed that "snap list" lists all installed packages nicely, but it does not fit pacui's format, which means i have to parse the output (since there is no option to get machine readable output).

 - flatpak installs platforms and dependencies. 
 - packages in flatpak have no simple names but e.g. "org.gimp.GIMP", which is a pain to type. 
 - "flatpak list" has the same problem as "snap list"

because i use neither snap nor flatpak, i think that i am the wrong person to integrate support for these package management systems into pacui.

**Comment by excalibur1234** [comment]
if there was another CLI applikation, which can update and cleanup snap and flatpak packages, i am happy to integrate support for it in pacui. if this application is found on the user's system, it could be called from within pacui. i could list it as an optional dependency of pacui.

**Comment by excalibur1234** [comment]
when i want to integrate support for updating of snap/flatpak packages only, is it enough to use the following commands?

- when `snapd` is installed:
`sudo snap refresh`

- when `flatpak` is installed:
`flatpak update -y`

that should be rather simple to include.

**Comment by puxplaying** [comment]
> when i want to integrate support for updating of snap/flatpak packages only, is it enough to use the following commands?
> 
>     * when `snapd` is installed:
>       `sudo snap refresh`
> 
>     * when `flatpak` is installed:
>       `flatpak update -y`
> 
> 
> that should be rather simple to include.

In general that should be enough to update both. However Flatpak has not the same ability as snap to clean up itself and therefore i would also suggest to run
`flatpak uninstall --unused --delete-data -y`
after the flatpak update at least in the maintain function of pacui.

**Comment by excalibur1234** [comment]
alright.
i think i will implement it in the 'maintain' option.

and does flatpak need root privileges (i.e. sudo) or not?

**Comment by puxplaying** [comment]
Flatpak does not require root privileges. Thank you!

**Comment by excalibur1234** [comment]
i have just pushed this commit, which should include snap and flatpak updates: https://github.com/excalibur1234/pacui/commit/165b4040a1b2d411f2890eb5657d3989cab0806a

can you check it and report back, whether it works as you expect it?

**Comment by puxplaying** [comment]
This looks very good. One question, did you not want to include the update functionality for both in `func_m` too? Would be nice for people like me who prefer to run the maintain option only.

**Pull request closed without merging**
